#PEDIDOS

@baseUrl = http://localhost:8080/pedidos

### GET - Obtener todos los pedidos
GET {{baseUrl}}

### GET - Obtener pedidos por ID
GET {{baseUrl}}/2

### POST - Crear pedidos
POST  {{baseUrl}}
Content-Type: application/json

{
    "nombre_producto": "Zapatillas",
    "cantidad_producto": 2,
    "estado_pedido": "En proceso",
    "total": 20000
}

### PUT - Actualizar pedidos
PUT {{baseUrl}}/2
Content-Type: application/json

{
    "nombre_producto": "Polera",
    "cantidad_producto": 4,
    "estado_pedido": "En transito",
    "total": 10000
}

### DELETE elimina un producto segun la id
DELETE {{baseUrl}}/3